### ISSUE TITLE
Misuse of the word "kernel"

### ISSUE THREAD

**Issue by stropitek** [image-js/image-js-docs#101]
![CleanShot 2024-02-13 at 15 14 27](https://github.com/image-js/image-js-docs/assets/4118690/feb05a49-d89b-41ee-8b2e-ae4856f4e703)

I don't think we can call it a "kernel" if it does not have values.

Check other pages (dilation etc.)

**Comment by EscapedGibbon** [comment]
> ![CleanShot 2024-02-13 at 15 14 27](https://private-user-images.githubusercontent.com/4118690/304440484-feb05a49-d89b-41ee-8b2e-ae4856f4e703.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODk2NTYsIm5iZiI6MTcwODA4OTM1NiwicGF0aCI6Ii80MTE4NjkwLzMwNDQ0MDQ4NC1mZWIwNWE0OS1kODliLTQxZWUtOGIyZS1hZTQ4NTZmNGU3MDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTZUMTMxNTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmE0MmFmMjc1N2E4NjE4MGY0OTk2YWNmODRhYjNiMWE5Mjc2ZTdiMTE5MzRjM2Q0OWVkYWQ4MDRmNzYzYmE0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iiK2Cmhu59OGuPkqDtBrXFhf0oBnSoWg09aKuDAwMeY)
> 
> I don't think we can call it a "kernel" if it does not have values.
> 
> Check other pages (dilation etc.)

I am not sure about it.  I have seen several instances where the structuring element is referred as "kernel".
 (for example here is a link that I took from dilate.ts file
http://docs.opencv.org/2.4/doc/tutorials/imgproc/erosion_dilatation/erosion_dilatation.html).
We can use a more specific term, like structuring element, but then I suppose we need to change the option name for these functions since we call them "kernel" as well.
